MvcRatings/Models/Song.cs
using System.ComponentModel.DataAnnotations;

namespace MvcRatings.Models
{

    public class Song
    {
        [Key] public int Id { get; set; }

        [Display(Name = "Title")] public string Title { get; set; }
        
        [Display(Name = "ArtistId")] public int ArtistId { get; set; }
        [Display(Name = "Artist")]
        public Artist? Artist {
            get;
            set;
        }
        [Display(Name = "AlbumId")] public int? AlbumId { get; set; }
        [Display(Name = "Album")]
        public Album? Album {
            get;
            set;
        }

        [Display(Name = "Release Date")] public DateTime ReleaseDate { get; set; }

        [Display(Name = "Duration")] public TimeSpan Duration { get; set; }

        public ICollection<Rating>? Ratings { get; set; }

    }
}

MvcRatings/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcRatings.Models;
using MvcRatings.Data;

namespace MvcRatings.Controllers
{
    // [Route("api/[controller]")]
    // [ApiController]
    public class RatingMaker
    {
        public Song so {get;set;} = new();
        public Guid uid {get;set;} = new();
        public DateTime date {get;set;} = new();
        public int val { get; set; } = new();
        public string com { get; set; }
    }
    public class RatingController : Controller
    {
        private readonly ContextDb _context;

        public RatingController(ContextDb context)
        {
            _context = context;
        }
        
        public ActionResult AddRating(int id)
        {   
            var lol = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            foreach (Rating r in _context.Rating.Where(r => r.SongId==id))
            {
                if (lol == r.UserId)
                {
                    return RedirectToAction("DetailsSong", "Song", new { id = id });
                }
            }
            RatingMaker rm = new RatingMaker();
            
            rm.uid = lol;
            rm.date = DateTime.Now;
            rm.so = _context.Song.Where(a => a.Id == id).ToList().First();
            return View(rm);
        }
        
        public async Task<ActionResult<Album>> SaveRating(RatingMaker model)
        {
            try
            {
                Rating r = new Rating();
                r.Value = model.val;
                r.Comment = model.com;
                r.SongId = model.so.Id;
                r.UserId = model.uid;
                r.Date = model.date;
                
                _context.Rating.Add(r);
                _context.SaveChanges();
                return RedirectToAction("DetailsSong","Song", new { id = model.so.Id});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        
        // GET: api/Rating
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Rating>>> GetRating()
        {
            /*
            var xd = _context.Rating.Include(r => r.Song).ToList().First().Song; |teraz działa bez include nie działa

            var aa = _context.Rating.Where(r => r.Song.Title == "asdasd")  |działa  .ToList().First().Song; |nie działa potrzebuje include
            */
            
          if (_context.Rating == null)
          {
              return NotFound();
          }
            return await _context.Rating.ToListAsync();
        }

        // GET: api/Rating/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Rating>> GetRating(int id)
        {
          if (_context.Rating == null)
          {
              return NotFound();
          }
            var rating = await _context.Rating.FindAsync(id);

            if (rating == null)
            {
                return NotFound();
            }

            return rating;
        }

        // PUT: api/Rating/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutRating(int id, Rating rating)
        {
            if (id != rating.Id)
            {
                return BadRequest();
            }

            _context.Entry(rating).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RatingExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Rating
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Rating>> PostRating(Rating rating)
        {
          if (_context.Rating == null)
          {
              return Problem("Entity set 'ContextDb.Rating'  is null.");
          }
            _context.Rating.Add(rating);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetRating", new { id = rating.Id }, rating);
        }

        // DELETE: api/Rating/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteRating(int id)
        {
            if (_context.Rating == null)
            {
                return NotFound();
            }
            var rating = await _context.Rating.FindAsync(id);
            if (rating == null)
            {
                return NotFound();
            }

            _context.Rating.Remove(rating);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool RatingExists(int id)
        {
            return (_context.Rating?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MvcRatings/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcRatings.Models;
using MvcRatings.Data;
using Microsoft.AspNetCore.Authorization;
namespace MvcRatings.Controllers
{
    public class Srate
    {
        public List<Song> so {get;set;}
        public List<Rating> ras {get;set;}
        public Srate()
        {
            this.so = new List<Song>();
            this.ras = new List<Rating>();
        }
    }
    public class SongMaker
    {
        public Album al {get;set;} = new();
        public TimeSpan dur { get; set; } = new();
        public string tit { get; set; }
    }
    // [Route("api/[controller]")]
    // [ApiController]
    public class SongController : Controller
    {
        private readonly ContextDb _context;

        public SongController(ContextDb context)
        {
            _context = context;
        }
        // GET: Song/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        
        // POST: Song/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            var songs = await _context.Song
                .Include(s => s.Artist) 
                .Where(s => s.Title.Contains(SearchPhrase))
                .ToListAsync();
            return PartialView("_SearchResults", songs);
        }
        [Authorize]
        public ActionResult AddSong(int id)
        {
            SongMaker sm = new SongMaker();
            sm.al = _context.Album.Where(a => a.Id == id).ToList().First();
            return View(sm);
        }
        [Authorize]
        public async Task<ActionResult<Album>> SaveSong(SongMaker model)
        {
            try
            {
                Song s = new Song();
                s.Title = model.tit;
                s.ReleaseDate = model.al.ReleaseDate;
                s.ArtistId = model.al.ArtistId;
                s.AlbumId = model.al.Id;
                s.Duration = model.dur;
                
                _context.Song.Add(s);
                _context.SaveChanges();
                return RedirectToAction("DetailsAlbum","Album", new { id = model.al.Id});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [Authorize]
        public async Task<IActionResult> RemoveSong(bool confirm, int id)
        {
            
                if (_context.Song == null)
                {
                    return NotFound();
                }

                var song = await _context.Song.FindAsync(id);
                if (song == null)
                {
                    return NotFound();
                }

                int? back = song.AlbumId;
                
                _context.Song.Remove(song);
                await _context.SaveChangesAsync();
                return RedirectToAction("DetailsAlbum","Album", new { id = back});
            
        }
        public async Task<IActionResult> DetailsSong(int Id)
        {
            if (_context.Song == null)
            {
                return Problem("Entity set 'BangerBumper.Song'  is null.");
            }

            Srate sra = new Srate();
            
            sra.so = _context.Song.Where(a => a.Id == Id).Include(b=>b.Album).Include(o=>o.Artist).ToList();
            sra.ras = await _context.Rating.Include(r => r.Song).Where(r => r.Song.Id == Id).Include(b=>b.User).ToListAsync();
            return View(sra);
        }
        
        
        // GET: api/Song
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Song>>> GetSong()
        {
          if (_context.Song == null)
          {
              return NotFound();
          }
            return await _context.Song.ToListAsync();
        }

        // GET: api/Song/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Song>> GetSong(int id)
        {
          if (_context.Song == null)
          {
              return NotFound();
          }
            var song = await _context.Song.FindAsync(id);

            if (song == null)
            {
                return NotFound();
            }

            return song;
        }

        // PUT: api/Song/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutSong(int id, Song song)
        {
            if (id != song.Id)
            {
                return BadRequest();
            }

            _context.Entry(song).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SongExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Song
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Song>> PostSong(Song song)
        {
          if (_context.Song == null)
          {
              return Problem("Entity set 'ContextDb.Song'  is null.");
          }
            _context.Song.Add(song);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetSong", new { id = song.Id }, song);
        }

        // DELETE: api/Song/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSong(int id)
        {
            if (_context.Song == null)
            {
                return NotFound();
            }
            var song = await _context.Song.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            _context.Song.Remove(song);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool SongExists(int id)
        {
            return (_context.Song?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MvcRatings/Views/Song/AddSong.cshtml
@model MvcRatings.Controllers.SongMaker
@{
    ViewData["Title"] = "AddSong";
}

<h1>Add song to: @Model.al.Title </h1>

<div class="container" style="width:40%;margin-top:2%">

    @using (Html.BeginForm("SaveSong", "Song", FormMethod.Post))
    {   
        @Html.HiddenFor(model => model.al.Id)
        @Html.HiddenFor(model => model.al.ArtistId)
        @Html.HiddenFor(model => model.al.ReleaseDate)
        @Html.TextBoxFor(model => model.tit, new { @class = "form-control", @placeholder = "Title" })
        @Html.TextBoxFor(model => model.dur, new { @class = "form-control", @placeholder = "Duration" })
        <input type="submit" value="Submit" class="btn btn-block btn-primary" />

    }

</div>

<div>
    <a type="button" class="btn btn-primary" asp-controller="Album" asp-action="DetailsAlbum" asp-route-id="@Model.al.Id" >Go back to the album</a>
</div>

MvcRatings/Views/Song/DetailsSong.cshtml
@model MvcRatings.Controllers.Srate
@{
    ViewData["Title"] = "DetailsSong";
}

<div class="text-center">
    <h1 class="display-3">@Html.DisplayFor(modelItem => modelItem.so[0].Title)</h1>
    <h3 class="display-6"> by: @Html.DisplayFor(modelItem => modelItem.so[0].Artist.Name)</h3>
    <h3 class="display-6"> from: @Html.DisplayFor(modelItem => modelItem.so[0].Album.Title)</h3>
    <h5 class="display-10"> released on: @Html.DisplayFor(modelItem => modelItem.so[0].ReleaseDate)</h5>
    <h5 class="display-10"> is: @Html.DisplayFor(modelItem => modelItem.so[0].Duration) long</h5>
    <p>Bumps:</p>
</div>

<p>
    <a type="button" class="btn btn-primary" asp-controller="Rating" asp-action="AddRating" asp-route-id="@Model.so[0].Id" >Add new BUMP</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ras[0].Value)
        </th>
        <th>
            User
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ras[0].Comment)
        </th>
        <th>
            Date of BUMPing
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.ras)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.FirstName)
                @Html.DisplayFor(modelItem => item.User.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
    }
    </tbody>
</table>

<div>
    <a type="button" class="btn btn-primary" asp-controller="Album" asp-action="DetailsAlbum" asp-route-id="@Model.so[0].AlbumId" >Go back to the album</a>
</div>

MvcRatings/Views/Song/ShowSearchForm.cshtml
@{
    ViewData["Title"] = "ShowSearchForm";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowSearchForm</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<h1>Search song by title: </h1>

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form id="searchForm" method="post">
            <div class="form-group mb-3">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control"/>
            </div>

            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div id="searchResults"></div>

<script>
    $(document).ready(function () {
        $('#searchForm').on('submit', function (event) {
            event.preventDefault();

            $.ajax({
                url: '/Song/ShowSearchResults',
                type: 'POST',
                data: $(this).serialize(),
                success: function (data) {
                    $('#searchResults').html(data);
                }
            });
        });
    });
</script>

MvcRatings/Views/Song/_SearchResults.cshtml
@model IEnumerable<MvcRatings.Models.Song>

<table class="table">
    <thead>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Release Date</th>
        <th>Duration</th>
        <th>Show Details</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var song in Model)
    {
    <tr>
        <td>@Html.DisplayFor(modelItem => song.Title)</td>
        <td>@Html.DisplayFor(modelItem => song.Artist.Name)</td>
        <td>@Html.DisplayFor(modelItem => song.ReleaseDate)</td>
        <td>@Html.DisplayFor(modelItem => song.Duration)</td>
        <td>
            <a type="button" class="btn btn-primary" asp-controller="Song" asp-action="DetailsSong" asp-route-id="@song.Id">Details</a>
        </td>
    </tr>
    }
    </tbody>
</table>